// <auto-generated />
using System;
using GestaoArmazens.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20221102200345_UpdatedArmazemTable2")]
    partial class UpdatedArmazemTable2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GestaoArmazens.Domain.Armazens.Armazem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Altitude")
                        .HasColumnType("double");

                    b.Property<string>("Designacao")
                        .HasColumnType("longtext");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Armazens");
                });

            modelBuilder.Entity("GestaoArmazens.Domain.Entregas.Entrega", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Peso")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("TempoCarregamento")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("TempoDescarregamento")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("GestaoArmazens.Domain.Armazens.Armazem", b =>
                {
                    b.OwnsOne("GestaoArmazens.Domain.Armazens.Morada", "Morada", b1 =>
                        {
                            b1.Property<string>("ArmazemId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("CodigoPostal")
                                .HasColumnType("longtext");

                            b1.Property<string>("Localidade")
                                .HasColumnType("longtext");

                            b1.Property<int>("NumeroPorta")
                                .HasColumnType("int");

                            b1.Property<string>("Pais")
                                .HasColumnType("longtext");

                            b1.Property<string>("Rua")
                                .HasColumnType("longtext");

                            b1.HasKey("ArmazemId");

                            b1.ToTable("Armazens");

                            b1.WithOwner()
                                .HasForeignKey("ArmazemId");
                        });

                    b.Navigation("Morada");
                });
#pragma warning restore 612, 618
        }
    }
}
