// <auto-generated />
using System;
using GestaoArmazens.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20221102192643_UpdatedArmazemTable")]
    partial class UpdatedArmazemTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GestaoArmazens.Domain.Armazens.Armazem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Altitude")
                        .HasColumnType("double");

                    b.Property<string>("Designacao")
                        .HasColumnType("longtext");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Morada")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Armazens");
                });

            modelBuilder.Entity("GestaoArmazens.Domain.Entregas.Entrega", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Peso")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("TempoCarregamento")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("TempoDescarregamento")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
